[package]
name = "shader_sandbox"
version = "0.1.0"
authors = ["Gabriel Martinez <reitaka@gmail.com>"]

[dependencies]
clap = "*"
conrod = "*"
fps_counter = "*"
gfx = "*"
#inotify = "*"
#notify = "*"
piston = "*"
piston_window = "*"
piston2d-gfx_graphics = "*"
piston2d-graphics = "*"
pistoncore-sdl2_window = "*"
