[package]
name = "shader_sandbox"
version = "0.1.0"
authors = ["Gabriel Martinez <reitaka@gmail.com>"]

[dependencies]
chrono = "^0.3.0"
clap = "^2.23.3"
conrod = "^0.51.1"
fps_counter = "^0.2.0"
glium = { version = "^0.14.0", features = [], default-features = false }
midgar = { path = "../../games/midgar-engine/midgar" }
#notify = "^4.0.1"
